### ISSUE TITLE
broadcast_parameters is not exported for stable release

### ISSUE THREAD

**Issue by dnabanita7** [avik-pal/FluxMPI.jl#13]
``broadcast_parameters`` is exported only in FluxMPI#main

**Comment by avik-pal** [comment]
Which release are you on? `broadcast_parameters` seems to be exported https://github.com/avik-pal/FluxMPI.jl/blob/2952955d83f46a178e9b4d4b27500d3f5887a76a/src/FluxMPI.jl#L23
