### ISSUE TITLE
 Warning: MPI Implementation is not CUDA Aware.

### ISSUE THREAD

**Issue by brendanwallison** [avik-pal/FluxMPI.jl#38]
I get this error when I import this package. Brand new to MPI in Julia--any thoughts on how to pin down the root cause?

**Comment by avik-pal** [comment]
That is not an error. It is just saying that your OpenMPI build is not CUDA aware. Refer to the docs https://avik-pal.github.io/FluxMPI.jl/dev/common_gotchas/#cuda-aware-mpi
